### ISSUE TITLE
Buddies

### ISSUE THREAD

**Issue by nutty85** [nutty323/paper#3]
Love

0x471B0fd9200927Ca46D1E84E8bcBCBc7EA9B551B

0xead0b58ad123a744404E39d2635E00FbDe973643

GBPX6X6VYLZMEVHSEJCC6UTLQDHIGYFTXPUU2R3CZ767WWSGZ7BEXI47

**Comment by nutty85** [comment]
Love

**Comment by nutty323** [comment]
Fixed
